### ISSUE TITLE
Protoc version error with sentencepiece

### ISSUE THREAD

**Issue by summacod** [tensorflow/text#313]
ERROR: /home/XXXX/Downloads/text/tensorflow_text/core/kernels/BUILD:310:18: C++ compilation of rule '//tensorflow_text/core/kernels:sentencepiece_kernels' failed (Exit 1)
In file included from tensorflow_text/core/kernels/sentencepiece_kernels.cc:23:
bazel-out/k8-opt/bin/external/com_google_sentencepiece/src/sentencepiece.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
   17 | #error This file was generated by an older version of protoc which is
      |  ^~~~~
bazel-out/k8-opt/bin/external/com_google_sentencepiece/src/sentencepiece.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
   18 | #error incompatible with your Protocol Buffer headers. Please
      |  ^~~~~
bazel-out/k8-opt/bin/external/com_google_sentencepiece/src/sentencepiece.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
   19 | #error regenerate this file with a newer version of protoc.
      |  ^~~~~
Target //oss_scripts/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.338s, Critical Path: 4.10s
INFO: 5 processes: 5 local.
FAILED: Build did NOT complete successfully

**Comment by summacod** [comment]
Linux Ubuntu 20.04
    TensorFlow installed from source latest nightly build for Cuda 11
    TensorFlow-text version: Latest from source
    Python version: 3.8.2
    Installed using virtualenv? NO
    Bazel version (if compiling from source): 3.1.0
    GCC/Compiler version (if compiling from source): 9.3.0
    CUDA/cuDNN version: 11.0
    GPU model and memory: GeForce RTX 2070 8G

**Comment by broken** [comment]
I noticed this with our builds too. I'll submit a fix soon.

**Comment by broken** [comment]
#326 was opened as a duplicate of this. I explained more there on why we are seeing it, and a manual fix you could make if you want to build immediately.

**Comment by broken** [comment]
We've update to work with tf 2.3.x and released 2.3.0-rc1. This should be resolved.
